-- === Nextcloud ===
CREATE DATABASE IF NOT EXISTS ``
  CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS ''@'192.168.%' IDENTIFIED BY '';
GRANT ALL PRIVILEGES ON ``.* TO ''@'192.168.%';

-- === WordPress ===
CREATE DATABASE IF NOT EXISTS ``
  CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS ''@'10.0.0.100' IDENTIFIED BY '';
GRANT ALL PRIVILEGES ON ``.* TO ''@'10.0.0.100';

-- === MediaWiki ===
CREATE DATABASE IF NOT EXISTS ``
  CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS ''@'10.0.0.100' IDENTIFIED BY '';
GRANT ALL PRIVILEGES ON ``.* TO ''@'10.0.0.100';

FLUSH PRIVILEGES;
